-- SQLite raw SQL for service icons and starter service content.
-- Run the ALTER TABLE line once if your services table does not already have icon_class.
ALTER TABLE services ADD COLUMN icon_class TEXT NULL;

INSERT INTO services (
    title,
    slug,
    excerpt,
    description,
    benefits,
    faqs,
    image,
    icon_class,
    meta_title,
    meta_description,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES
('Commercial Cleaning', 'commercial-cleaning', 'Reliable scheduled cleaning for commercial premises, communal spaces and client-facing environments.', 'Professional commercial cleaning for offices, retail spaces, communal areas and managed properties. Crestwell builds practical cleaning routines that protect your workplace standards and brand presentation.', '["Consistent cleaning standards","Flexible daily, weekly or periodic schedules","Suitable for offices, retail and shared facilities","Clear communication and service checks"]', '[{"question":"Do you offer Commercial Cleaning for commercial clients?","answer":"Yes. Crestwell is designed for commercial, property and facilities-led clients, with residential support available where appropriate."},{"question":"Can I request a recurring schedule?","answer":"Yes. We can quote for one-off, daily, weekly, fortnightly or custom recurring arrangements."},{"question":"How do I get a quote?","answer":"Use the quote form, call the team or send a WhatsApp enquiry with your property type, location and required service."}]', 'service/service_box_1.png', 'fa-solid fa-building', 'Commercial Cleaning | Crestwell Facilities', 'Commercial cleaning by Crestwell Facilities for offices, retail, communal areas and managed properties.', 10, 1, datetime('now'), datetime('now')),
('Office Cleaning', 'office-cleaning', 'Daily and periodic office cleaning for productive, presentable workplaces.', 'Office cleaning built around real working environments, from desks and meeting rooms to washrooms, kitchens, reception areas and high-touch surfaces.', '["Early morning, evening or out-of-hours options","Workstation, washroom and kitchen care","Supports staff wellbeing and visitor confidence","Recurring plans for growing teams"]', '[{"question":"Do you offer Office Cleaning for commercial clients?","answer":"Yes. Crestwell supports commercial and office teams with flexible schedules."},{"question":"Can I request out-of-hours cleaning?","answer":"Yes. We can discuss early morning, evening or other practical timing options."},{"question":"How do I get a quote?","answer":"Send the quote form, call, or use WhatsApp with your office size, postcode and preferred frequency."}]', 'service/service_box_2.png', 'fa-solid fa-broom', 'Office Cleaning | Crestwell Facilities', 'Office cleaning by Crestwell Facilities for productive, professional workplaces.', 20, 1, datetime('now'), datetime('now')),
('End of Tenancy Cleaning', 'end-of-tenancy-cleaning', 'Detailed handover cleaning for landlords, agents and tenants.', 'A thorough clean for rental property handovers, helping properties present professionally for inspections, new tenants and marketing.', '["Kitchen and bathroom detail cleaning","Agent and landlord friendly service","Improves presentation before viewings","One-off booking availability"]', '[{"question":"Do you clean before tenant handover?","answer":"Yes. This service is designed for move-outs, landlord checks and agent handovers."},{"question":"Can landlords and agents book directly?","answer":"Yes. We support landlords, agents, tenants and property managers."},{"question":"How do I get a quote?","answer":"Share the property type, location and required timing through the quote form, phone or WhatsApp."}]', 'service/service_box_3.png', 'fa-solid fa-spray-can-sparkles', 'End of Tenancy Cleaning | Crestwell Facilities', 'End of tenancy cleaning for landlords, agents, tenants and managed properties.', 30, 1, datetime('now'), datetime('now')),
('Airbnb / Serviced Accommodation Cleaning', 'airbnb-serviced-accommodation-cleaning', 'Fast, reliable turnover cleaning for short-stay properties.', 'Guest-ready cleaning for Airbnb and serviced accommodation operators who need consistent standards, responsive scheduling and smooth changeovers.', '["Turnaround cleaning between stays","Linen and presentation support ready","Reliable standards for guest reviews","Scalable for multiple units"]', '[{"question":"Can you support guest turnovers?","answer":"Yes. Crestwell can support short-stay and serviced accommodation changeovers."},{"question":"Can this scale across multiple units?","answer":"Yes. We can discuss repeat schedules for single or multiple properties."},{"question":"How do I get a quote?","answer":"Send your property count, location, turnover timing and service needs."}]', 'service/service_box_1.png', 'fa-solid fa-house-chimney', 'Airbnb Cleaning | Crestwell Facilities', 'Airbnb and serviced accommodation cleaning for reliable guest-ready turnovers.', 40, 1, datetime('now'), datetime('now')),
('Deep Cleaning', 'deep-cleaning', 'Intensive cleaning for neglected, high-use or priority spaces.', 'Deep cleaning for spaces needing more than routine maintenance, including detailed surface care, washrooms, kitchens, high-touch areas and hard-to-reach zones.', '["Ideal before launches, inspections or reopenings","Targets built-up dirt and high-use areas","Supports hygiene and presentation goals","Available for commercial and residential spaces"]', '[{"question":"When should I book deep cleaning?","answer":"Deep cleaning is useful before inspections, reopenings, handovers or after heavy use."},{"question":"Can you deep clean commercial spaces?","answer":"Yes. Crestwell supports commercial, property and residential environments."},{"question":"How do I get a quote?","answer":"Share the space type, location and priority areas through the quote form."}]', 'service/service_box_2.png', 'fa-solid fa-soap', 'Deep Cleaning | Crestwell Facilities', 'Deep cleaning for commercial, property and residential spaces needing detailed attention.', 50, 1, datetime('now'), datetime('now')),
('Facilities Support', 'facilities-support', 'Practical support services for managed buildings and operations.', 'Facilities support for businesses, landlords and property managers needing dependable cleaning-led operational assistance as their portfolio grows.', '["Scalable facilities service structure","Supports property managers and operators","Recurring and ad hoc support options","Professional reporting and communication"]', '[{"question":"Is this only cleaning?","answer":"The service is cleaning-led facilities support for managed buildings and operational spaces."},{"question":"Can you support property managers?","answer":"Yes. Crestwell is built for landlords, agents, operators and property management needs."},{"question":"How do I get a quote?","answer":"Send the building type, service requirement and coverage area."}]', 'service/service_box_3.png', 'fa-solid fa-briefcase', 'Facilities Support | Crestwell Facilities', 'Facilities support for managed buildings, landlords, property managers and operators.', 60, 1, datetime('now'), datetime('now')),
('Pressure Washing', 'pressure-washing', 'Exterior surface cleaning for entrances, paths and hardstanding areas.', 'Pressure washing for commercial frontages, paths, driveways, bin stores, courtyards and external surfaces that shape first impressions.', '["Improves kerb appeal","Suitable for commercial and residential exteriors","Removes surface grime and weathering","Supports periodic property maintenance"]', '[{"question":"What areas can be pressure washed?","answer":"Common areas include entrances, paths, driveways, courtyards, bin stores and hardstanding areas."},{"question":"Can this be recurring?","answer":"Yes. We can quote one-off or periodic exterior cleaning."},{"question":"How do I get a quote?","answer":"Send photos, location and the approximate surface area where possible."}]', 'service/service_box_1.png', 'fa-solid fa-hand-sparkles', 'Pressure Washing | Crestwell Facilities', 'Pressure washing for entrances, paths, courtyards, driveways and exterior surfaces.', 70, 1, datetime('now'), datetime('now')),
('Emergency Cleaning', 'emergency-cleaning', 'Responsive cleaning for urgent incidents and short-notice needs.', 'Emergency cleaning support for spills, property issues, guest changeover pressure, event aftermath and urgent commercial presentation needs.', '["Short-notice response","Useful for incidents and urgent handovers","Commercial and property-focused support","Clear scope before attendance"]', '[{"question":"Can I request urgent cleaning?","answer":"Yes. Availability depends on timing and location, but urgent enquiries are welcome."},{"question":"What situations can you support?","answer":"Spills, urgent handovers, event aftermath, guest turnover pressure and short-notice presentation needs."},{"question":"How do I get a quote?","answer":"Call or WhatsApp first for urgent needs, then send any supporting details."}]', 'service/service_box_2.png', 'fa-solid fa-truck-fast', 'Emergency Cleaning | Crestwell Facilities', 'Emergency cleaning support for urgent incidents, handovers and short-notice needs.', 80, 1, datetime('now'), datetime('now')),
('Property Management Cleaning', 'property-management-cleaning', 'Cleaning support for landlords, agents and managed property portfolios.', 'Property management cleaning for communal areas, void properties, serviced accommodation, inspections and recurring maintenance routines.', '["Designed for portfolios and managed sites","Supports inspections and tenant experience","Recurring communal cleaning options","One-off and ongoing plans"]', '[{"question":"Do you support managed portfolios?","answer":"Yes. Crestwell can support landlords, agents and property managers with repeat cleaning needs."},{"question":"Can you clean communal areas?","answer":"Yes. Communal spaces, void properties and inspection preparation can be discussed."},{"question":"How do I get a quote?","answer":"Share your portfolio type, location, property count and service frequency."}]', 'service/service_box_3.png', 'fa-solid fa-warehouse', 'Property Management Cleaning | Crestwell Facilities', 'Cleaning support for landlords, agents and managed property portfolios.', 90, 1, datetime('now'), datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
    title = excluded.title,
    excerpt = excluded.excerpt,
    description = excluded.description,
    benefits = excluded.benefits,
    faqs = excluded.faqs,
    image = excluded.image,
    icon_class = excluded.icon_class,
    meta_title = excluded.meta_title,
    meta_description = excluded.meta_description,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = datetime('now');
