<?php

return [
    'name' => 'CRESTWELL FACILITIES',
    'tagline' => 'Clean Spaces. Strong Impressions.',
    'logo' => env('SITE_LOGO', 'logo.svg'),
    'logo_white' => env('SITE_LOGO_WHITE', 'logo-white.svg'),
    'footer_logo' => env('SITE_FOOTER_LOGO', 'logo-footer.svg'),
    'phone' => env('SITE_PHONE', '+44 0000 000000'),
    'phone_link' => env('SITE_PHONE_LINK', '+440000000000'),
    'email' => env('SITE_EMAIL', 'info@crestwellfacilities.com'),
    'whatsapp' => env('SITE_WHATSAPP', '+440000000000'),
    'address' => env('SITE_ADDRESS', 'United Kingdom'),
    'business_hours' => env('SITE_BUSINESS_HOURS', 'Mon-Fri : 09.00 am-05.00 pm<br>Sunday Closed'),
    'footer_about' => env('SITE_FOOTER_ABOUT', "We're your trusted cleaning company, dedicated to consistently delivering exceptional cleaning service."),
    'newsletter_text' => env('SITE_NEWSLETTER_TEXT', 'Subscribe to our latest articles, news resources, hints and product updates.'),
    'facebook_url' => env('SITE_FACEBOOK_URL', 'https://www.facebook.com/'),
    'twitter_url' => env('SITE_TWITTER_URL', 'https://www.twitter.com/'),
    'linkedin_url' => env('SITE_LINKEDIN_URL', 'https://www.linkedin.com/'),
    'instagram_url' => env('SITE_INSTAGRAM_URL', 'https://www.instagram.com/'),
    'youtube_url' => env('SITE_YOUTUBE_URL', 'https://www.youtube.com/'),
    'google_maps_embed' => env('SITE_GOOGLE_MAPS_EMBED', 'https://www.google.com/maps?q=United%20Kingdom&output=embed'),
    'google_review_url' => env('SITE_GOOGLE_REVIEW_URL', '#'),
    'analytics_id' => env('SITE_GOOGLE_ANALYTICS_ID'),
    'lead_recipient' => env('SITE_LEAD_RECIPIENT', env('SITE_EMAIL', 'info@crestwellfacilities.com')),
];
